# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Configuration

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name : Test Customer Directory
      working-directory: ./customer
      run: |
        npm ci
        npm run jest

    - name : Test Product Directory
      working-directory: ./product
      run: |
        npm ci
        npm run jest

    - name : Test Shopping Directory
      working-directory: ./shopping
      run: |
        npm ci
        npm run jest
